name: Backend deploy
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: unbuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version}}
              uses: actions/setup-node@v2
              with:
                node-version: ${{ matrix.node-version }}
            - name: Yarn Install
              run: yarn install
              working-directory: Backend
            - name: Backend Build
              run: yarn build
              working-directory: Backend
              env:
                CI: ""
            - name: Deploy to S3
              uses: jakejarvis/s3-sync-action@master
              env:
                AWS_S3_BUCKET: ${{ secrets.AWS_PROD_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                SOURCE_DIR: "Backend/build"